services:
  app:
    image: ghcr.io/sodo0005/dv1677-ht26-grupp10.1-backend:latest
    container_name: dv1677-ht26-grupp10.1-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
    restart: always